server:
  port: 9002
spring:
  application:
    name: cloudalibaba-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 43.143.137.232:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'