server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaopangio/springcloud-config.git
          search-paths:
            - springcloud-config
      label: master
  rabbitmq:
    host: 43.143.137.232
    port: 5672
    username: admin
    password: admin
eureka:
    instance:
        prefer-ip-address: true
        instance-id: cloud-config-center
    client:
        service-url:
          defaultZone: http://myeureka7001.com:7001/eureka
        register-with-eureka: true
        fetch-registry: true
#        暴露bus刷新配置端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"