server:
  port: 7001
eureka:
  instance:
    hostname: myeureka7001.com
  client:
#    表示不像注册中心注册自己
    register-with-eureka: false
#    表示自己就是注册中心，
    fetch-registry: false
#    设置eureka server服务的地址，后续的服务注册和服务查询都需要
    service-url:
      defaultZone: http://myeureka7002.com:7002/eureka/
# 服务保护机制
  server:
#    关闭自我保护机制，保证不可用的服务及时被剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000