server:
  port: 8001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://myeureka7001.com:7001/eureka
  instance:
    instance-id: hystrix-payment8001
    prefer-ip-address: true


spring:
  application:
    name: cloud-provider-hystrix-payment